# Generated by Django 5.1.2 on 2024-10-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=120)),
                ('speed', models.FloatField(default=45)),
            ],
        ),
    ]
